{"uuid": "a4f6423b-76aa-4bcf-b861-e3423422412d", "children": ["d65f9a4b-b686-4181-a95d-f579e471b54c"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. \n\n", "trace": "  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\myDev\\PeiYou_AutoTest\\testcase\\conftest.py\", line 40, in start_appium_desired\n    driver = appium_desired_caps(host, port, system_port)\n  File \"C:\\myDev\\PeiYou_AutoTest\\base\\DesireCaps.py\", line 42, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub'%(host,port), desired_caps)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 144, in __init__\n    proxy\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595054010904, "stop": 1595054057654}], "start": 1595054010904, "stop": 1595054057874}